server:
  port: 7070
  context-path: /api

security:
  oauth2:
    resource:
      jwt:
        key-value: 
                  -----BEGIN PUBLIC KEY-----
                  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmTkggU+TC0A4O3uHaGt0
                  xUSPcUc6m4g66tgJeYMZbjZjJ+hu90ua4igYCAoNLIWStk4sDhrtp1D/gqOjRA31
                  8MAcUifI6TLKBaf9pVVyivnHX7ugHYTD/nkpqdHYfBcQtIsdVlhkDJTIuUKRQ94s
                  QQedhKy1yvJ9hqx95EobnsqqrUrcXD4/PvOI0HmznV/4ZvGCP/0PG0frmznVtyzy
                  FuXEi03Y8KecMa0C4Av840u2cwnF2/ncBeOZPVJDOFqRZNm5I6mLPW/XPDEBwo8G
                  V5CDkIy5gLgRYhohGch+fozdJ3mlbiVRwSnpFKp2sErIM3XRLDo8L+O53tIIR9T6
                  bQIDAQAB
                  -----END PUBLIC KEY-----
   

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  
    url: jdbc:mysql://220.230.124.242:33306/cnsblog
    username: cnsblog
    password: cnsblog


mybatis:
    type-aliases-package: com.cnsblog.api.web.domain
    mapper-locations: classpath:mappers/*.xml