 CREATE TABLE USER (
	LOGIN_ID VARCHAR(50),
	USER_ID  VARCHAR(50),
	PASSWORD VARCHAR(200),
	ROLE_TYPE VARCHAR(2),
	REG_DATE DATE,
	LAST_DATE DATE,
	PRIMARY KEY (LOGIN_ID)
 );

  CREATE TABLE USER_ROLE (
	ROLE_TYPE VARCHAR(2),
	ROLE_NM VARCHAR(20),
	PRIMARY KEY (ROLE_TYPE)
 );
